### ISSUE TITLE
SassC-Rails upgrade - support CSS `min()` and `max()`

### ISSUE THREAD

**Issue by injms** [alphagov/finder-frontend#1124]
Replacing 
```ruby
gem 'sass-rails', '~> 5.0'
```
with
```ruby
gem 'sassc-rails', '>= 2.0.1'
```
results in errors that (I think) are to do with the conflict between CSS's `max()` and Sass's `max()`. 

[SassC Rails](https://github.com/sass/sassc-rails) uses [SassC Ruby](https://github.com/sass/sassc-ruby), which uses [Libsass](https://github.com/sass/libsass). Unfortunately, Libsass doesn't currently support CSS `min()` and `max()` - [issue 2701](https://github.com/sass/libsass/issues/2701).

Slightly strange is when SassC Rails is used the app runs fine with no errors, but the tests fail. This might be to do with some gems still relying and installing on Ruby Sass, such as GOV.UK Publishing Components ([just updated](https://github.com/alphagov/govuk_publishing_components/pull/853) in [v16.7.0](https://github.com/alphagov/govuk_publishing_components/pull/854)) and the deprecated [GOV.UK Frontend Toolkit](https://github.com/alphagov/govuk_frontend_toolkit).

The error thrown is:
```
Error: "calc(0px)" is not a number for `max'
```

The Sass function also doesn't like having `calc()` added to it, since `calc()` will only work in the browser. Sass can't compute percentages, since they rely on knowing the window width - for example: `calc(100% - 1em)` can only be worked out when you know how big 100% is.

This is triggered by the [width container](https://github.com/alphagov/govuk-frontend/blob/master/src/objects/_width-container.scss#L13) element in GOV.UK Frontend:
```scss
@supports (margin: unquote("max(calc(0px))"))
```
When the library supports CSS min/max, the unquote function ensures that this is output as CSS instead of being processed as a Sass max function.

## Solutions:
 * ~Wait for Libsass support~ (No longer an option as [Libsass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated))
 * Use Dart Sass which [already supports CSS `min` and `max`](https://github.com/sass/dart-sass/pull/428) - but I haven't been able to find a Rails-friendly way of doing that
 * Use [Webpacker](https://www.github.com/rails/webpacker) to use Webpack to compile the CSS. This would mean making sure that all JavaScript and CSS dependencies are JavaScript modules rather than gems. See [Ticket 505 on GOV.UK Publishing Components](https://github.com/alphagov/govuk_publishing_components/issues/505).

**Comment by kevindew** [comment]
@laurentqro may have found a solution to the dual compilation problem in: https://github.com/alphagov/whitehall/pull/4998/commits/1ae8699230617783533979d77b9d71a54198b752

That involves turning off the css compressor and setting the sass style to :compressed

**Comment by KludgeKML** [comment]
I'm going to close this issue as we now use DartSass for this app and although there are still a few kinks to work out in terms of CSS functions, they're the same for all apps using DartSass across GOV.UK, and the frontend community are working out the solution elsewhere.
