### ISSUE TITLE
Search facet's / pills not removable

### ISSUE THREAD

**Issue by dashouse** [alphagov/finder-frontend#1261]
The facet / pills / tags are not currently removable. They get added correctly but interacting with them to remove has no effect and throws a JS error.

<img width="1116" alt="Screen Shot 2019-07-17 at 08 44 27" src="https://user-images.githubusercontent.com/23356842/61357016-602e6400-a86f-11e9-859e-ca5cb9a6d6b3.png">

**Comment by andysellick** [comment]
@dashouse I might know what's causing this, can you provide the URL of the page this is happening on?

**Comment by dashouse** [comment]
Thanks :)

Seems to be happening whenever I search but here's a URL `https://www.gov.uk/search/all?parent=&keywords=test&level_one_taxon=&manual=&public_timestamp%5Bfrom%5D=&public_timestamp%5Bto%5D=&topical_events=&order=relevance`

**Comment by andysellick** [comment]
@bilbof

**Comment by andysellick** [comment]
How to reproduce:

- go to https://www.gov.uk/help/cookies
- choose `off` for all cookie settings and click `save`
- do any keyword search and click on the facet tag

Thanks @dashouse for reproducing this!
