### ISSUE TITLE
Transition email topic is out of date

### ISSUE THREAD

**Issue by tijmenb** [alphagov/finder-frontend#1912]
I just subscribed to the transition check email and got this:
 
<img width="1082" alt="Screenshot 2020-02-03 at 20 03 31" src="https://user-images.githubusercontent.com/233676/73686709-6d525980-46c0-11ea-8dec-6c84298f55fa.png">

Looks like this needs an update:

https://github.com/alphagov/finder-frontend/blob/7aa6970d8f9e62f2b766a8c449d24d68c2374100/app/controllers/brexit_checker_controller.rb#L57

**Comment by koetsier** [comment]
Thanks for reporting this Tijmen!

We're deploying a fix shortly.

**Comment by koetsier** [comment]
This is now fixed, so closing this issue
