### ISSUE TITLE
Respect metadata facet ordering

### ISSUE THREAD

**Issue by dsingleton** [alphagov/finder-frontend#194]
Finder schemas define facets in a meaningful order, that should be preserved when displaying metadata for a result. ([Example of schema ordered facets](https://github.com/alphagov/govuk-content-schemas/blob/master/formats/policy/frontend/examples/policy_area.json#L34-L53))

This order is changed (slightly) by finder-frontend. They'll be re-ordered so all text metadata fields are displayed first followed by date fields (but maintaining their order within those groups), eg:

![screenshot 2015-04-29 17 18 45](https://cloud.githubusercontent.com/assets/63201/7395792/38ed1434-ee94-11e4-8d47-8891cb364e4d.png)

This is cased by https://github.com/alphagov/finder-frontend/blob/master/app/models/document.rb#L48, and I think it should be as simple as refactoring the metadata code to loop over all facets, selecting the display method by type, instead.

This would match the longer term plans of introducing `Metadata` models, which could be of different types, eg date or text.

**Comment by tommyp** [comment]
Nice PNG.

**Comment by tijmenb** [comment]
Closing this, we're not likely to pick this up directly. I'm sure that if this surfaces again as a problem we'll be able to fix it.

**Comment by tommyp** [comment]
Hi Tijmen.

**Comment by tijmenb** [comment]
👋

**Comment by dsingleton** [comment]
😢
