### ISSUE TITLE
Why is `enable-aria-controls.js` needed?

### ISSUE THREAD

**Issue by andysellick** [alphagov/finder-frontend#2535]
A question in https://github.com/alphagov/finder-frontend/pull/2519 by @owenatgov asked why do we have a script https://github.com/alphagov/finder-frontend/blob/main/app/assets/javascripts/modules/enable-aria-controls.js that applies an `aria-controls` attribute to an element, when this could be applied directly in markup?

Looking through the code, this module appears to only be called once, by the [date filter component](https://github.com/alphagov/finder-frontend/blob/main/app/views/components/_date-filter.html.erb#L12). This partial is passed a value for the `aria-controls` attribute by the [date_facet template](https://github.com/alphagov/finder-frontend/blob/main/app/views/finders/_date_facet.html.erb#L8), which the date filter then passes through to the input component.

This is all used to create the date inputs in the filters on the [search page](https://www.gov.uk/search/all?keywords=minister&order=relevance). If you look, they have their `aria-controls` attributes set to the main search area, so that when users update those fields there is that association to indicate to users that the main search results have been updated.

Setting aside the question of the [value of aria-controls](https://heydonworks.com/article/aria-controls-is-poop/) I'm still left a bit confused what all of this is for. I thought maybe `aria-controls` was only being applied when JS was enabled, but it also seems to be there when JS is turned off.

I put some logging into my local version and the script is initialised on the search page but doesn't appear to then operate on any elements. I repeated the test using the previous jQuery version of the script and got the same result.

I'm left with:

- the script was intended to apply `aria-controls` only if JS was enabled, but somehow that got changed at some point
- the script acted on something else that has since been removed
- a third option that I've missed 🤔 

cc @leenagupte

**Comment by leenagupte** [comment]
@andysellick Does that mean it's not actually being removed? Should we remove it?

**Comment by andysellick** [comment]
I was hoping that by raising this issue someone with more knowledge than me would jump in and provide some more information. I'll give it a bit of time and then look at removing it if no-one's responded.

**Comment by kevindew** [comment]
As per https://github.com/alphagov/finder-frontend/pull/2595 this script wasn't needed anymore and was deleted.

The last usage of this was removed in 2018: https://github.com/alphagov/finder-frontend/commit/af5b72012911bc2d84ec4af86811f5109d063d6a#diff-f90fee1f2d7d2b2341b403e10727271b70bd61e365b4ea19e7df1e9fcf789e19
