### ISSUE TITLE
Is hidden search 'Skip to results' link in the right place?

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/finder-frontend#2841]
The GOV.UK search has a hidden link `Skip to results` shown on focus. I'd like to query if it's in the right location on the page / working as expected.

I *think* it used to be placed at the start of the filters. Now it appears to be right next to the results:
<img width="1075" alt="Screenshot 2022-08-02 at 17 34 15" src="https://user-images.githubusercontent.com/2204224/182426912-b99fcda4-6a12-4f2e-8154-a38549c681fe.png">

If the purpose is to save keyboard only and screen reader users the pain of tabbing through a bunch of things - I don't think we're helping much as it's so close to the results. I think it used to be before the filters themselves where it saved a bunch of tabbing.

**Comment by andysellick** [comment]
Interesting, thanks @edwardhorsford. Yes, I think it used to be at the start of the filters too. I'll have a look.

**Comment by edwardhorsford** [comment]
Thanks @andysellick!
