### ISSUE TITLE
Application components not rendering correctly

### ISSUE THREAD

**Issue by andysellick** [alphagov/finder-frontend#3047]
Logging this last thing on a Friday in case I forget. I just noticed that the components in `finder-frontend` don't appear to be rendering properly in the component guide (see below), although they seem to be okay in the rest of the application.

I've only been able to test this locally as the live `finder-frontend` component guide isn't online at the moment.

e.g. the expander component:

![Screenshot 2023-04-28 at 16 07 00](https://user-images.githubusercontent.com/861310/235185244-59040f35-7d67-4de1-9b5d-e57c38896d61.png)

**Comment by andysellick** [comment]
@MartinJJones is this possibly related to the recent application.scss compiling work that we talked about recently?

**Comment by MartinJJones** [comment]
@andysellick yes, this PR will fix this issue as well - https://github.com/alphagov/govuk_publishing_components/pull/3347

**Comment by andysellick** [comment]
@MartinJJones just tested and yep, all fixed, great stuff.

Don't worry about the styling - it shouldn't be styled, and the message I think is clear enough.
