### ISSUE TITLE
Update site search to share code with finders

### ISSUE THREAD

**Issue by fofr** [alphagov/finder-frontend#375]
Search was a straight port from frontend in #313. There's some tech debt (duplication) to refactor out:

* [ ] Checkbox filters switched to option select component (see #374)
* [ ] Switch site search to use live_search.js and remove live_site_search.js – an older version of the script
* [ ] Use the same mustache template
* [ ] Use the same base layout and styles
* [ ] Use search component for search box

**Comment by tijmenb** [comment]
This tech debt is now tracked on the tech debt board: https://trello.com/c/C2BGFRfo

I've copied over the todos into the card, thanks for those.
